services:
  - type: web
    name: palabraflow
    env: python
    region: oregon
    plan: free
    rootDir: server
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 10000
      - key: TRANSFORMERS_CACHE
        value: /tmp/transformers
      - key: HF_HOME
        value: /tmp/huggingface
      - key: TOKENIZERS_PARALLELISM
        value: false
